site_name: Digital Citizenship
repo_url: https://github.com/teamdigitale/cittadinanza-digitale
pages:
    - Home: index.md
    - API playground: server.md
    - Notes: api-notes.md
theme: readthedocs
strict: true
extra_templates:
    - api/messaging.html
    - api/preferences.html
    - api/messaging-common.yaml
    - api/messaging-public.yaml
    - api/preferences.yaml
