# it:
#   code: ita
#   name: italiano
#   t:
#     active_lang: lingua attiva
#     cookiebar_accept: Accetto
#     cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
#     cookiebar_privacy_policy: Privacy policy
#     follow_us: seguici su
#     footer_address: Indirizzo
#     footer_address_sub: ''
#     footer_contacts: Contatti
#     footer_contacts_sub: ''
#     footer_link_privacy_policy: privacy policy
#     footer_link_toc: note legali
#     footer_title: ' '
#     lang_on_site: sito in italiano
#     navigation_menu_label: Menu di navigazione
#     navigation_menu_esc: esci dalla navigazione
#     scrolltop_label: torna all'inizio dei contenuti
#     search_form_label: cerca
#     search_form_off: disattiva il form di ricerca
#     search_form_on: attiva il form di ricerca
#     search_form_start: avvia la ricerca
#     site_subtitle: La comunità italiana degli sviluppatori di servizi pubblici
#     site_title: /Cittadinanza digitale
#     share_msg: condividi
#     skiplink_goto_content: vai ai contenuti
#     skiplink_goto_navigation: vai alla navigazione del sito
#     toggle_menu_label: accedi al menu

en:
  code: eng
  name: english
  t:
    active_lang: current language
    cookiebar_accept: Accept
    cookiebar_msg: We are using cookies to provide statistics that help us give you the best experience of our site. By continuing to use the site you are agreeing to our use of cookies.
    cookiebar_privacy_policy: Privacy policy
    follow_us: follow us
    footer_address: Address
    footer_address_sub: ''
    footer_contacts: Contacts
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_toc: terms and conditions
    footer_title: ' '
    lang_on_site: website in english
    navigation_menu_label: Navigation menu
    navigation_menu_esc: exit navigation
    scrolltop_label: back to contents
    search_form_label: Search
    search_form_off: exit search form
    search_form_on: enter search form
    search_form_start: start searching
    site_subtitle:
    site_title: /Digital Citizenship
    share_msg: share
    skiplinks_goto_content: go to content
    skiplinks_goto_navigation: go to site navigation
    toggle_menu_label: go to navigation

    home_hero:
    home_newsletter_title: Subscribe to our Newlsetter
    home_newsletter_placeholder: email address
    home_newsletter_button: Subscribe
    home_newsletter_footer:

    menu_item_projects: Projects
    menu_item_credits: Credits
    menu_item_tools: Tools
    menu_item_faq: FAQ
    menu_item_contacts: Contacts
